apiVersion: v1
kind: Service
metadata:
  name: adk-ai-agent-service
spec:
  type: NodePort
  selector:
    app: adk-ai-agent
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
